In [ ]:
## 2025.07.06 '-고'에 대한 논문 작성느라 만듦

from datetime import datetime

time = []#걸린 시간 체크 리스트
start_t = datetime.now() #시간 체크
time.append(datetime.now() - start_t) #시간간격 저장
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

In [2]:
from pathlib import Path
dir_path = Path(r"C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치")
v_folder = dir_path / "최신버전" / "v"
sen_folder = dir_path / "최신버전" / "sen"

for file in v_folder.glob('*.csv'):
    print(file)

C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\국립국어원 구어 말뭉치(버전 1.2)_일부(1,15)_v5.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\국립국어원 일상대화 말뭉치2020,2021_v5.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\세종_문어_형태분석_말뭉치_v5.csv

In [ ]:
import pandas as pd

#%% 1.1 v 파일 읽기: 55초 걸림.
df_v_list = []
for file in v_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        
        df_v_list.append(df)

In [ ]:
#%% 1.2 문장 파일 읽어오기
df_sen_list = []
for file in sen_folder.glob('*.csv'):
    print(file)
    
print('%%%%%1.2 문장 파일-sen2 읽기') 
for file in sen_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        df_sen_list.append(df)
df_sen_list[2].rename(columns={'docu_id': 'file_id'}, inplace=True)

%%%%%1.2 문장 파일-sen2 읽기

In [ ]:
df_v_list[2].head(10)
df_v_list[0].info()

In [ ]:
df_sen_list[2].head(10)

,ID,sen_id,form,file_id,Snum,category,자료명,저자,출판사,출판연도,구어/문어,매체,내용,분류기호
0,1,AA0001.5,1993/06/08,AA0001,5.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
1,2,AA0001.6,19,AA0001,6.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
2,3,AA0001.7,엠마누엘 웅가로 / 의상서 실내 장식품으로… 디자인 세계 넓혀,AA0001,7.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
3,4,AA0001.8,프랑스의 세계적인 의상 디자이너 엠마누엘 웅가로가 실내 장식용 직물 디자이너로 나섰다.,AA0001,8.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
4,5,AA0001.9,"웅가로는 침실과 식당, 욕실에서 사용하는 갖가지 직물제품을 디자인해 최근 파리의 갤...",AA0001,9.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
5,6,AA0001.10,"목욕가운부터 탁자보, 냅킨, 앞치마까지 그가 디자인한 작품들에서 두드러지는 것은 색...",AA0001,10.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
6,7,AA0001.11,"남미풍의 강렬한 원색끼리의 조화, 수채화 같이 안온한 배색 등 색의 분위기를 강조하...",AA0001,11.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
7,8,AA0001.12,"엠마누엘 웅가로는 ""실내 장식품을 디자인할 때 옷을 만들 때와는 다른 해방감을 느낀...",AA0001,12.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
8,9,AA0001.13,집은 창작의 원천이라는 그는 옷 못지않게 공간이 주는 미학을 중요시해 왔다.,AA0001,13.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
9,10,AA0001.14,"매일 욕실에서 1시간 반 이상을 보낸다는 그는 체조와 텔레비전 시청, 식사까지 할 ...",AA0001,14.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115

In [10]:
df_v_list[0]

,ID,sen_id,word_id,word_id2,form/label,N_form,N_label,V_form,V_label,EP_form,...,file_id,docu_num,category,공공성,상호작용성,즉흥성,year,V_form_0,V_label_0,V_No
0,4,SBRW1900012479.1.1.3,2,2,안녕하/VA + 시/EP + ㅂ니까/EF + ?/SF,NaN,NULL,안녕하,VA,시,...,SBRW1900012479,1,방송대화,공적,대화,NULL,2019.0,안녕하,VA,2058
1,11,SBRW1900012479.1.1.4,7,7,비화되/VV + 곤/EC,NaN,NULL,비화되,VV,NULL,...,SBRW1900012479,1,방송대화,공적,대화,NULL,2019.0,비화되,VV,4999
2,12,SBRW1900012479.1.1.4,8,8,하/VX + ㅂ니다/EF + ./SF,NaN,NULL,하,VX,NULL,...,SBRW1900012479,1,방송대화,공적,대화,NULL,2019.0,하,VX,102
3,15,SBRW1900012479.1.1.5,3,3,밝혀지/VV + ㄴ/ETM,NaN,NULL,밝혀지,VV,NULL,...,SBRW1900012479,1,방송대화,공적,대화,NULL,2019.0,밝혀지,VV,3388
4,21,SBRW1900012479.1.1.5,9,9,불러오/VV + ㄴ/ETM,NaN,NULL,불러오,VV,NULL,...,SBRW1900012479,1,방송대화,공적,대화,NULL,2019.0,불러오,VV,4999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3698167,5449162,SBRW1900000475.1.1.774,3,3,없/VA + 고/EC,NaN,NULL,없,VA,NULL,...,SBRW1900000475,1,방송인터뷰,공적,대화,NULL,2019.0,없,VA,2004
3698168,5449172,SBRW1900000475.1.1.774,13,13,지원금/NNG + 이/VCP + 에요/EF + ./SF,지원금,NNG,이,VCP,NULL,...,SBRW1900000475,1,방송인터뷰,공적,대화,NULL,2019.0,이,VP,1001
3698169,5449174,SBRW1900000475.1.1.775,2,2,필요하/VA + ㄴ데/EC,NaN,NULL,필요하,VA,NULL,...,SBRW1900000475,1,방송인터뷰,공적,대화,NULL,2019.0,필요하,VA,2015
3698170,5449175,SBRW1900000475.1.1.775,3,3,공개하/VV + 자/EF + ./SF,NaN,NULL,공개하,VV,NULL,...,SBRW1900000475,1,방송인터뷰,공적,대화,NULL,2019.0,공개하,VV,3480
3698171,5449187,SBRW1900000475.1.1.779,3,3,의원/NNG + 이/VCP + 었/EP + 습니다/EF + ./SF,의원,NNG,이,VCP,었,...,SBRW1900000475,1,방송인터뷰,공적,대화,NULL,2019.0,이,VP,1001

In [15]:
#누락값 채움. 
#object를 category형으로 바꿈. : 45초 걸림
exclude_cols = ['form/label', 'N_form', 'V_form', 'f_V_form']  # 제외할 열
for df in df_v_list:
    for col in df.columns:
        if col in exclude_cols:
            continue  # 제외할 열은 건너뛰기

        # 숫자형이면 -1로 채움
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(-1)

        # 문자열(object)이면 'NULL'로 채우고 고유값 적을 때만 category로
        elif pd.api.types.is_object_dtype(df[col]):
            df[col] = df[col].fillna('NULL')
            unique_ratio = df[col].nunique(dropna=False) / len(df)
            if unique_ratio < 0.5:
                df[col] = df[col].astype('category')

In [14]:
import numpy as np

### 추가 정보 붙이는 함수 선언
def process_dataframe(result_df):    
    # 피벗테이블을 일반 데이터프레임으로 변환
    if 'index' in result_df.columns:
        result_df = result_df.reset_index()
    
    # category 덧붙이기
    if 'category' in result_df.columns:    
        data = {
            "category": ["강의", "강의, 학술집담회", "낭독", "뉴스", "방송대화", "방송인터뷰", "토론",
                        "교육자료", "사회일반", "신문", "인문", "일상대화", "자연", "잡지", "체험기술",
                        "총류,일반", "허구", "협력적대화"],
            "category1": ["공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어",
                        "문어", "문어", "문어", "문어", "사적구어", "문어", "문어", "문어",
                        "문어", "문어", "사적구어"]
        }
        df_category = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_category, on="category", how="left")

    # V_label 덧붙이기
    if 'V_label' in result_df.columns:
        data = {
            "V_label": ["VV", "VA", "VCN", "VCP", "XSV", "XSA", "VX"],
            "V_label_0": ["VV", "VA", "VA", "VP", "VV", "VA", "VX"]
        }
        df_v_label = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_v_label, on="V_label", how="left")

    # EN 정보 덧붙이기
    if 'EN_No' in result_df.columns:
        result_df['EN_No'] = pd.to_numeric(result_df['EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['EN_No_0'] = result_df['EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['EN_No_1'] = result_df['EN_No'] - result_df['EN_No_0']  # 소수점 이하만 남김

    # f_EN 정보 덧붙이기
    if 'f_EN_No' in result_df.columns:
        result_df['f_EN_No'] = pd.to_numeric(result_df['f_EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['f_EN_No_0'] = result_df['f_EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['f_EN_No_1'] = result_df['f_EN_No'] - result_df['f_EN_No_0']  # 소수점 이하만 남김
        
    # EP 정보 덧붙이기
    if 'EP_form' in result_df.columns:
        result_df['T'] = result_df['EP_form'].str.contains('았|었')
        result_df['M'] = result_df['EP_form'].str.contains('겠|겄')
        result_df['H'] = result_df['EP_form'].str.contains('시')

    # f_EP 정보 덧붙이기
    if 'f_EP_form' in result_df.columns:
        result_df['f_T'] = result_df['f_EP_form'].str.contains('았|었')
        result_df['f_M'] = result_df['f_EP_form'].str.contains('겠|겄')
        result_df['f_H'] = result_df['f_EP_form'].str.contains('시')

    # V_No 정보 덧붙이기
    if 'V_No' in result_df.columns:
        # V_label 생성: V_No 값에 따라 부여
        def assign_v_label(v_no):
            if 0 <= v_no < 1000:
                return 'VX'
            elif 1000 <= v_no < 2000:
                return 'VC'
            elif 2000 <= v_no < 3000:
                return 'VA'
            elif 3000 <= v_no < 5000:
                return 'VV'
            else:
                return ''  # 혹시 범위 벗어난 경우 대비

        result_df['V_label'] = result_df['V_No'].apply(assign_v_label)
    
    return result_df

In [18]:
def generate_pivot_statistics(
    df_list,
    index_columns,
    process_fn=None,
    filter_fn=None,
):
    """
    여러 DataFrame에서 지정한 index_columns 기준으로 피벗 통계를 계산.

    Parameters:
        df_list (list of pd.DataFrame): 분석 대상 데이터프레임 리스트
        index_columns (list of str): 피벗 기준 열 목록
        process_fn (callable, optional): 결과 df 후처리 함수 (예: process_dataframe)
        filter_fn (callable, optional): 각 df에 필터를 적용할 함수 (예: lambda df: df[df['V_label'] == 'VX'])

    Returns:
        pd.DataFrame: 통합된 피벗 통계 결과
    """
    result_df_list = []
    print(f"*** 통계를 만듭니다. ***")
    
    for i, df in enumerate(df_list):
        print(f"{i}. 피벗 생성 중...")

        # 필터 함수가 있다면 적용
        if filter_fn:
            df = filter_fn(df)

        cross_0 = pd.pivot_table(
            df[['ID'] + index_columns],
            index=index_columns,
            aggfunc='count',
            fill_value=0,
            dropna=True,
            observed=False
        )
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']]
        result_df_list.append(cross_0)

    result_df = pd.concat(result_df_list).reset_index()

    if process_fn:
        result_df = process_fn(result_df)

    return result_df

In [20]:
prefix = "V_EN"
save_folder = '2025.07.05-고'
index_columns = ['V_No', 'f_EN_label','f_EN_No']

def my_filter2(df):
    return df[(df['vx_len']==0) & (df['vx_no.']==-1)]

result_df = generate_pivot_statistics(
    df_list=df_v_list,
    index_columns=index_columns,
    process_fn=process_dataframe,
    filter_fn=my_filter2
)

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / save_folder / f'{prefix}_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

*** 통계를 만듭니다. ***
0. 피벗 생성 중...
1. 피벗 생성 중...
2. 피벗 생성 중...
***저장합니다.:    2025-07-05 16:24:52.332773***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_statistics_2025-07-05_16-24.csv (175,859행) ***

In [30]:
def generate_sentence_df(
    df_list,
    df_sen_list,
    process_fn=None,
    filter_fn=None,
):
    """
    DataFrame에서 필터를 수행한 결과를 문장과 합해서 출력

    Parameters:
        df_list (list of pd.DataFrame): 분석 대상 데이터프레임 리스트
        df_sen_list (list of pd.DataFrame): 합할 문장 데이터프레임 리스트
        process_fn (callable, optional): 결과 df 후처리 함수 (예: process_dataframe)
        filter_fn (callable, optional): 각 df에 필터를 적용할 함수 (예: lambda df: df[df['V_label'] == 'VX'])

    Returns:
        result_df_list: list of pd.DataFrame: 통합된 데이터프레임 리스트 결과
    """
    result_df_list = []
    print(f"*** 문장 통합 df를 만듭니다. ***")
    
    for i, (df, df_sen) in enumerate(zip(df_list, df_sen_list)):
        print(f"{i}. 통합 중...")

        # 필터 함수가 있다면 적용
        if filter_fn:
            df = filter_fn(df)

        if process_fn:
            result_df = process_fn(result_df)

        df_sen = df_sen[['sen_id', 'form']]
        result_df = pd.merge(df_sen, df, how='right', on = 'sen_id')
        print(f"{i}. 통합 완료..., 결과: {len(result_df)}")

        result_df_list.append(result_df)
    return result_df_list

In [ ]:
### .2 리스트에 문장 합하기. 검색용
print(f"***vx_sen_df를 만듭니다.:    {datetime.now()}***")

df_vx_sen_list = []
for i, (df, df_sen) in enumerate(zip(df_vx_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    print(f"{i}.***파 일:    {folder_name_list[i]}***")
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    df_vx_sen_list.append(df_vx_sen)
    
df_con = pd.concat(df_vx_sen_list)

print(f"***리스트를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_list2_' + timestamp + '.csv'
df_con.to_csv(out_file)

In [ ]:

prefix = "VX_V_No"
save_folder = 'result_2025'
index_columns = ['V_label', 'EP_form', 'EN_label', 'EN_No']

index_columns = ['V_No','vx1_No','EP_form', 'EN_label']

def my_filter2(df):
    return df[(df['vx_len']==1) & (df['vx_no.']==-1) & ((df['EP_form']==1101)&(df['f_EN_No']<1102))]

result_df = generate_pivot_statistics(
    df_list=df_v_list,
    index_columns=index_columns,
    process_fn=process_dataframe,
    filter_fn=my_filter2
)

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / save_folder / f'{prefix}_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

*** 통계를 만듭니다. ***
0. 피벗 생성 중...
1. 피벗 생성 중...
2. 피벗 생성 중...
***저장합니다.:    2025-06-20 08:36:33.391284***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\result_2025\VX_V_No_statistics_2025-06-20_08-36.csv (30,518행) ***

In [19]:
print(result_df.shape)
result_df
result_df.to_csv(out_file, index=False, encoding='utf-8-sig')
result_df.info()

(44502, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44502 entries, 0 to 44501
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   category   44502 non-null  object
 1   V_label    44502 non-null  object
 2   EP_form    44502 non-null  object
 3   EN_label   44502 non-null  object
 4   EN_No      44502 non-null  float64
 5   ID         44502 non-null  int64
 6   category1  27622 non-null  object
 7   V_label_0  41765 non-null  object
 8   EN_No_0    44502 non-null  int64
 9   EN_No_1    44502 non-null  float64
 10  T          44502 non-null  bool
 11  M          44502 non-null  bool
 12  H          44502 non-null  bool
dtypes: bool(3), float64(2), int64(2), object(6)
memory usage: 3.5+ MB

In [ ]:
from tqdm import tqdm

def generate_grouped_pivot(
    df_list,
    index_columns,
    group_column='V_No',
    process_fn=None,
    filter_fn=None
):
    result_df_list = []
    print(f"*** V_No 단위로 피벗 수행 시작 ***")
    
    for i, df in enumerate(df_list):
        print(f"📄 파일 {i} 처리 중")

        if filter_fn:
            df = filter_fn(df)  # 전체 df에 1차 필터

        grouped = df.groupby(group_column)
        
        for v_no, group_df in tqdm(grouped, desc=f'  → group별 처리 ({i})'):
            if len(group_df) == 0:
                continue

            if filter_fn:
                group_df = filter_fn(group_df)  # V_No별 group_df에도 필터 적용

            if len(group_df) == 0:
                continue

            cross = pd.pivot_table(
                group_df[['ID'] + index_columns],
                index=index_columns,
                aggfunc='count',
                fill_value=0,
                dropna=True,
                observed=False
            )
            cross = cross[cross['ID'] != 0][['ID']]
            cross = cross.reset_index()
            cross[group_column] = v_no  # ✅ V_No도 결과에 같이 넣어줘야 나중에 분석 편함

            result_df_list.append(cross)

    if result_df_list:
        result_df = pd.concat(result_df_list).reset_index(drop=True)
    else:
        result_df = pd.DataFrame(columns=index_columns + ['ID', group_column])

    if process_fn:
        result_df = process_fn(result_df)

    return result_df

In [75]:
prefix = "category_VX"
index_columns = ['category','EP_form', 'vx1_No','f_EP_form']
# 예: EN_No가 결측이 아닌 경우만 사용
def my_filter(df):
    return df[((df['EN_No']>=1101)&(df['EN_No']<1102))|((df['EN_No']>=1401)&(df['EN_No']<1402))|((df['EN_No']>=1171)&(df['EN_No']<1172))|((df['EN_No']>=1411)&(df['EN_No']<1412))]

def my_filter2(df):
    return df[(df['vx_len']==1) & (df['vx_no.']==-1) & ((df['f_EN_No']>=1101)&(df['f_EN_No']<1102))]

In [76]:
result_df = generate_grouped_pivot(
    df_list=df_v_list,
    index_columns=index_columns,
    group_column=index_columns[0],
    process_fn=process_dataframe,
    filter_fn=my_filter2
)

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_75332\1221139255.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)

*** V_No 단위로 피벗 수행 시작 ***
📄 파일 0 처리 중

  → V_No별 처리 (0): 100%|██████████| 7/7 [00:03<00:00,  2.23it/s]

📄 파일 1 처리 중

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_75332\1221139255.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)
  → V_No별 처리 (1): 100%|██████████| 2/2 [00:00<00:00,  8.00it/s]

📄 파일 2 처리 중

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_75332\1221139255.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby(group_column)
  → V_No별 처리 (2): 100%|██████████| 9/9 [00:04<00:00,  2.00it/s]

In [70]:
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / save_folder / f'{prefix}_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

***저장합니다.:    2025-06-20 09:00:31.063079***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\result_2025\VX_V_No_statistics_2025-06-20_09-00.csv (39,684행) ***