In [1]:
from datetime import datetime

time = []#걸린 시간 체크 리스트
start_t = datetime.now() #시간 체크
time.append(datetime.now() - start_t) #시간간격 저장
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

In [2]:
from pathlib import Path
dir_path = Path(r"C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치")
v_folder = dir_path / "최신버전" / "v"
sen_folder = dir_path / "최신버전" / "sen"

for file in v_folder.glob('*.csv'):
    print(file)

C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\국립국어원 구어 말뭉치(버전 1.2)_일부(1,15)_v5.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\국립국어원 일상대화 말뭉치2020,2021_v5.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\v\세종_문어_형태분석_말뭉치_v5.csv

In [3]:
import pandas as pd

#%% 1.1 v 파일 읽기
df_v_list = []
for file in v_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        
        df_v_list.append(df)

df_v_list[2].rename(columns={'docu_id': 'file_id'}, inplace=True)

In [29]:
df

,ID,sen_id,word_id,word_id2,form/label,N_form,N_label,V_form,V_label,EP_form,...,v_loc_w,vx_0,vx_no.,EN_No,f_EN_No,file_id,category,V_form_0,V_label_0,V_No
0,12,AA0001.7,10,10,넓히/VV + 어/EF,NaN,NULL,넓히,VV,NULL,...,-1.0,NULL,-1,1401.0,1401.0,AA0001,신문,넓히,VV,3743
1,14,AA0001.8,2,2,세계/NNG + 적/XSN + 이/VCP + ㄴ/ETM,세계 + 적,XSN,이,VCP,NULL,...,-1.0,NULL,-1,2001.1,2001.1,AA0001,신문,이,VP,1001
2,23,AA0001.8,11,11,나서/VV + 었/EP + 다/EF + ./SF,NaN,NULL,나서,VV,었,...,-1.0,NULL,-1,1101.0,1101.0,AA0001,신문,나서,VV,3132
3,28,AA0001.9,5,5,사용하/VV + 는/ETM,NaN,NULL,사용하,VV,NULL,...,-1.0,NULL,-1,2001.2,2001.2,AA0001,신문,사용하,VV,3083
4,31,AA0001.9,8,8,디자인하/VV + 아/EC,NaN,NULL,디자인하,VV,NULL,...,-1.0,NULL,-1,20.0,20.0,AA0001,신문,디자인하,VV,4999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4599509,12973618,JO0153.993,15,15,않/VX + 으나/EC,NaN,NULL,않,VX,NULL,...,14.0,지/EC + 않/VX,201,238.0,238.0,JO0153,사회일반,않,VX,103
4599510,12973621,JO0153.993,18,18,받/VV + 는/ETM,NaN,NULL,받,VV,NULL,...,-1.0,NULL,-1,2001.2,2001.2,JO0153,사회일반,받,VV,3014
4599511,12973624,JO0153.993,21,21,억세/VA + ㄴ/ETM,NaN,NULL,억세,VA,NULL,...,-1.0,NULL,-1,2001.1,2001.1,JO0153,사회일반,억세,VA,2999
4599512,12973626,JO0153.993,23,23,때문/NNB + 이/VCP + ㄹ/ETM,때문,NNB,이,VCP,NULL,...,-1.0,NULL,-1,2002.0,1101.0,JO0153,사회일반,이,VP,1001
4599513,12973627,JO0153.993,24,24,것/NNB + 이/VCP + 다/EF + ./SF,것,NNB,이,VCP,NULL,...,23.0,ㄹ/ETM + 것/NNB + 이/VCP,800,1101.0,1101.0,JO0153,사회일반,이,VP,1001

In [4]:
df_v_list[2].head(10)
df_v_list[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3698172 entries, 0 to 3698171
Data columns (total 50 columns):
 #   Column      Dtype
---  ------      -----
 0   ID          int64
 1   sen_id      object
 2   word_id     int64
 3   word_id2    int64
 4   form/label  object
 5   N_form      object
 6   N_label     object
 7   V_form      object
 8   V_label     object
 9   EP_form     object
 10  EP_label    object
 11  EN_form     object
 12  EN_label    object
 13  J_form      object
 14  J_label     object
 15  vx_len      int64
 16  f_w_id      int64
 17  f_V_form    object
 18  f_V_label   object
 19  f_EP_form   object
 20  f_EP_label  object
 21  f_EN_form   object
 22  f_EN_label  object
 23  f_J_form    object
 24  f_J_label   object
 25  vx1         object
 26  vx1_No      int64
 27  vx2         object
 28  vx2_No      int64
 29  vx3         object
 30  vx3_No      int64
 31  vx4         object
 32  vx4_No      int64
 33  vx5         object
 34  vx5_No      int64
 35  v_loc_w     float64
 36  vx_0        object
 37  vx_no.      int64
 38  EN_No       float64
 39  f_EN_No     float64
 40  file_id     object
 41  docu_num    int64
 42  category    object
 43  공공성         object
 44  상호작용성       object
 45  즉흥성         object
 46  year        float64
 47  V_form_0    object
 48  V_label_0   object
 49  V_No        int64
dtypes: float64(4), int64(13), object(33)
memory usage: 1.4+ GB

In [5]:
#누락값 채움. 
#object를 category형으로 바꿈. 
exclude_cols = ['form/label', 'N_form', 'V_form', 'f_V_form']  # 제외할 열
for df in df_v_list:
    for col in df.columns:
        if col in exclude_cols:
            continue  # 제외할 열은 건너뛰기

        # 숫자형이면 -1로 채움
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(-1)

        # 문자열(object)이면 'NULL'로 채우고 고유값 적을 때만 category로
        elif pd.api.types.is_object_dtype(df[col]):
            df[col] = df[col].fillna('NULL')
            unique_ratio = df[col].nunique(dropna=False) / len(df)
            if unique_ratio < 0.5:
                df[col] = df[col].astype('category')

In [6]:
#%% 1.2 문장 파일 읽어오기
print('%%%%%1.2 문장 파일-sen2 읽기') 
df_sen_list = []
for file in sen_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        df_sen_list.append(df)
df_sen_list[2].rename(columns={'docu_id': 'file_id'}, inplace=True)

%%%%%1.2 문장 파일-sen2 읽기

In [7]:
df_sen_list[1].head(10)

,ID,sen_id,form,original_form,birthplace,principal_residence,current_residence,age,sex,education,occupation,file_id,docu_num,category,공공성,상호작용성,화자수,year,S_Len
0,1,SDRW2000000001.1.1.1,저는 여행 다니는 것을,저는 여행 다니는 것을,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,4
1,2,SDRW2000000001.1.1.2,굉장히 좋아하는데요.,굉장히 좋아하는데요.,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,2
2,3,SDRW2000000001.1.1.3,그래가지고,그래가지고,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,2
3,4,SDRW2000000001.1.1.4,스페인이나 뭐 영국,스페인이나 뭐 영국,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,3
4,5,SDRW2000000001.1.1.5,유럽,유럽,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,1
5,6,SDRW2000000001.1.1.6,아니면 국내에서도 뭐 강릉이나,아니면 국내에서도 뭐 강릉이나,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,4
6,7,SDRW2000000001.1.1.7,전주 같은 데를 많이 다녔는데,전주 같은 데를 많이 다녔는데,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,5
7,8,SDRW2000000001.1.1.8,혹시 여행 다니는 거,혹시 여행 다니는 거,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,4
8,9,SDRW2000000001.1.1.9,좋아하시나요?,좋아하시나요?,경기,경기,경기,20대,여성,대재,학생,SDRW2000000001,1,일상대화,사적,대화,2인,2020,1
9,10,SDRW2000000001.1.1.10,저 여행 다니는 거 되게 좋아해서,저 여행 다니는 거 되게 좋아해서,경기,경기,경기,20대,여성,대졸,전문가 및 관련 종사자,SDRW2000000001,1,일상대화,사적,대화,2인,2020,6

In [8]:
for df in df_sen_list:
    print(df.columns)

Index(['ID', 'sen_id', 'form', 'original_form', 'birthplace',
       'principal_residence', 'current_residence', 'age', 'sex', 'occupation',
       'file_id', 'docu_num', 'category', '공공성', '상호작용성', '즉흥성', 'year',
       'S_Len'],
      dtype='object')
Index(['ID', 'sen_id', 'form', 'original_form', 'birthplace',
       'principal_residence', 'current_residence', 'age', 'sex', 'education',
       'occupation', 'file_id', 'docu_num', 'category', '공공성', '상호작용성', '화자수',
       'year', 'S_Len'],
      dtype='object')
Index(['ID', 'sen_id', 'form', 'file_id', 'Snum', 'category', '자료명', '저자',
       '출판사', '출판연도', '구어/문어', '매체', '내용', '분류기호'],
      dtype='object')

In [13]:
import numpy as np

### 추가 정보 붙이는 함수 선언
def process_dataframe(result_df):    
    # 피벗테이블을 일반 데이터프레임으로 변환
    if 'index' in result_df.columns:
        result_df = result_df.reset_index()
    
    # category 덧붙이기
    if 'category' in result_df.columns and 'category' in df_category.columns:    
        data = {
            "category": ["강의", "강의, 학술집담회", "낭독", "뉴스", "방송대화", "방송인터뷰", "토론",
                        "교육자료", "사회일반", "신문", "인문", "일상대화", "자연", "잡지", "체험기술",
                        "총류,일반", "허구", "협력적대화"],
            "category1": ["공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어",
                        "문어", "문어", "문어", "문어", "사적구어", "문어", "문어", "문어",
                        "문어", "문어", "사적구어"]
        }
        df_category = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_category, on="category", how="left")

    # V_label 덧붙이기
    if 'V_label' in result_df.columns and 'V_label' in df_v_label.columns:
        data = {
            "V_label": ["VV", "VA", "VCN", "VCP", "XSV", "XSA", "VX"],
            "V_label_0": ["VV", "VA", "VA", "VP", "VV", "VA", "VX"]
        }
        df_v_label = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_v_label, on="V_label", how="left")

    # EN 정보 덧붙이기
    if 'EN_No' in result_df.columns:
        result_df['EN_No'] = pd.to_numeric(result_df['EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['EN_No_0'] = result_df['EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['EN_No_1'] = result_df['EN_No'] - result_df['EN_No_0']  # 소수점 이하만 남김

    # f_EN 정보 덧붙이기
    if 'f_EN_No' in result_df.columns:
        result_df['f_EN_No'] = pd.to_numeric(result_df['f_EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['f_EN_No_0'] = result_df['f_EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['f_EN_No_1'] = result_df['f_EN_No'] - result_df['f_EN_No_0']  # 소수점 이하만 남김
        
    # EP 정보 덧붙이기
    if 'EP_form' in result_df.columns:
        result_df['T'] = result_df['EP_form'].str.contains('았|었')
        result_df['M'] = result_df['EP_form'].str.contains('겠|겄')
        result_df['H'] = result_df['EP_form'].str.contains('시')

    # f_EP 정보 덧붙이기
    if 'f_EP_form' in result_df.columns:
        result_df['f_T'] = result_df['f_EP_form'].str.contains('았|었')
        result_df['f_M'] = result_df['f_EP_form'].str.contains('겠|겄')
        result_df['f_H'] = result_df['f_EP_form'].str.contains('시')
    return result_df

In [14]:
from pathlib import Path
label_path = Path(r"C:\Users\yu2hy\OneDrive\◎2020_copus\python_2023\label")
V_No_file = label_path / "000.V_No.csv"

#EP_No 파일을 읽고 df와 병합하여 결과를 반환하는 함수
def read_and_merge_EP_no(df, EP_No_file_path = label_path / "000.EP_label.csv", encoding='ansi'):
    """
    V_No 파일을 읽고 df와 병합하여 결과를 반환하는 함수
    
    Parameters:
    df (pd.DataFrame): 병합할 데이터프레임
    
    Returns:
    pd.DataFrame: 병합된 데이터프레임
    """    
    with open(EP_No_file_path, "r", encoding=encoding) as f:
        print(f"{V_No_file}를 읽어옵니다.        {datetime.now()}")
        df_No = pd.read_csv(f, low_memory=False)
    df_No_selected = df_No[['EP_form', 'EP_No']] # 필요한 열만 선택하여 병합 준비
    df_No_selected['EP_No'] = df_No_selected['EP_No'].replace('', -1).fillna(-1).astype(int) # 'EP_No' 열을 정수 형식으로 변환
    result_df = pd.merge(df, df_No_selected, on='EP_form', how='left') # 데이터프레임 병합
    return result_df

In [ ]:
#%% 문장 통계
print("***문장 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
index_columns = ['category', 'file_id']
for i, df in enumerate(df_sen_list):
        for column in index_columns:      #화자 정보 count를 위해서 빈값을 ''로 채우기
            df[column] = df[column].fillna('') 
        
        cross_0 = pd.pivot_table(df[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        
        result_df_list.append(cross_0)

result_df = pd.concat(result_df_list)

# 함수 호출
result_df = process_dataframe(result_df) #category 및 라벨 덧붙임. 

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / '2025.07.05-고' / f'sen_statistics_{timestamp}.csv'
result_df.to_csv(out_file)

***문장 통계를 위한 기본 파일을 만듭니다.
***저장합니다.:    2025-07-05 09:26:24.298847***

In [ ]:
#%% V 기본 통계
print("***V관련 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

index_columns = ['category', 'V_label','EP_form', 'EN_label', 'EN_No']

for i, df in enumerate(df_v_list):
        cross_0 = pd.pivot_table(df[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=True)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움

        result_df_list.append(cross_0)

result_df = pd.concat(result_df_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / 'result_2025' / f'v_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=False, encoding='utf-8-sig')

In [19]:
print(result_df.shape)
result_df
result_df.to_csv(out_file, index=False, encoding='utf-8-sig')
result_df.info()

(44502, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44502 entries, 0 to 44501
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   category   44502 non-null  object
 1   V_label    44502 non-null  object
 2   EP_form    44502 non-null  object
 3   EN_label   44502 non-null  object
 4   EN_No      44502 non-null  float64
 5   ID         44502 non-null  int64
 6   category1  27622 non-null  object
 7   V_label_0  41765 non-null  object
 8   EN_No_0    44502 non-null  int64
 9   EN_No_1    44502 non-null  float64
 10  T          44502 non-null  bool
 11  M          44502 non-null  bool
 12  H          44502 non-null  bool
dtypes: bool(3), float64(2), int64(2), object(6)
memory usage: 3.5+ MB

In [ ]:
#%% V_No 통계
import gc #메모리 자동 관리 도구인 Garbage Collection(쓰레기 수집) 을 제어할 수 있게 해 주는 표준 라이브러리

print("***용언 목록 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

index_columns = ['category', 'V_No', 'V_label', 'EP_form', 'EN_label', 'EN_No']
data = {
    "EN_label": ["EF", "EC", "ETM", "ETN", ""],
    "EN_label_0": [11100000, 22200000, 33300000, 44400000, -1]
}
df_en_label = pd.DataFrame(data)
for i, df in enumerate(df_v_list):
        for column in index_columns:      #화자 정보 count를 위해서 빈값을 ''로 채우기
            df[column] = df[column].fillna('') 
        
        df = read_and_merge_EP_no(df)
        df = pd.merge(df, df_en_label, on="EN_label", how="left")
        
        if 'EN_label' in df.columns and 'EN_No' in df.columns:
            df['EN_combined'] = df['EN_label_0'] + df['EN_No']  
           
        i_col = ['category', 'V_No', 'EP_No', 'EN_combined']
        grouped_df = df.groupby(index_columns).size().reset_index(name='ID')
        
        result_df_list.append(grouped_df)
        del grouped_df, column
        gc.collect()

result_df = pd.concat(result_df_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 정보 덧붙이기 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / 'result' / f'V_No_statistics_{timestamp}.csv'
result_df.to_csv(out_file)

***용언 목록 통계를 위한 기본 파일을 만듭니다.
C:\Users\yu2hy\OneDrive\◎2020_copus\python_2023\label\000.V_No.csv를 읽어옵니다.        2025-06-19 10:11:15.388852

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_63972\644724134.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_No_selected['EP_No'] = df_No_selected['EP_No'].replace('', -1).fillna(-1).astype(int) # 'V_No' 열을 정수 형식으로 변환

C:\Users\yu2hy\OneDrive\◎2020_copus\python_2023\label\000.V_No.csv를 읽어옵니다.        2025-06-19 10:11:20.134933

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_63972\644724134.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_No_selected['EP_No'] = df_No_selected['EP_No'].replace('', -1).fillna(-1).astype(int) # 'V_No' 열을 정수 형식으로 변환

C:\Users\yu2hy\OneDrive\◎2020_copus\python_2023\label\000.V_No.csv를 읽어옵니다.        2025-06-19 10:11:25.308607

C:\Users\yu2hy\AppData\Local\Temp\ipykernel_63972\644724134.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_No_selected['EP_No'] = df_No_selected['EP_No'].replace('', -1).fillna(-1).astype(int) # 'V_No' 열을 정수 형식으로 변환

***저장합니다.:    2025-06-19 10:11:31.723689***

In [ ]:
#%% 용언 목록 통계
print("***용언 목록 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

index_columns = ['category', 'V_label_0', 'V_form_0']

for i, df in enumerate(df_v_list):
        for column in index_columns:      #화자 정보 count를 위해서 빈값을 ''로 채우기
            df[column] = df[column].fillna('') 
        
        cross_0 = pd.pivot_table(df[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        
        result_df_list.append(cross_0)

result_df = pd.concat(result_df_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + 'v_form_statistics_' + timestamp + '.csv'
result_df.to_csv(out_file)
#%% EP, EN 통계
print("***V관련 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

index_columns = ['category', 'V_label', 'EP_form', 'EN_label', 'EN_No']

for i, df in enumerate(df_v_list):
        #조합을 확인하기 위해서 없는 경우를 채움.      
        for column in index_columns:
            if pd.api.types.is_numeric_dtype(df[column]):
                df[column] = df[column].fillna(-1)
            else:
                df[column] = df[column].fillna('__MISSING__')
        
        cross_0 = pd.pivot_table(df[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        
        result_df_list.append(cross_0)

result_df = pd.concat(result_df_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + 'v_statistics_' + timestamp + '.csv'
result_df.to_csv(out_file)

In [46]:
#%% EN 통계
print("***EN_관련 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장
index_columns = ['category','file_id', 'EN_label', 'EN_No', 'EN_form']

for i, df in enumerate(df_v_list):
    if index_columns:        
        #조합을 확인하기 위해서 없는 경우를 채움.      
        for column in index_columns:
            if pd.api.types.is_numeric_dtype(df[column]):
                df[column] = df[column].fillna(-1)
            else:
                df[column] = df[column].fillna('__MISSING__')
        
        cross_0 = pd.pivot_table(df[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=True)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        
        result_df_list.append(cross_0)

result_df = pd.concat(result_df_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / 'result' / f'en_statistics_{timestamp}.csv'
result_df.to_csv(out_file)

***EN_관련 통계를 위한 기본 파일을 만듭니다.
***저장합니다.:    2025-06-19 13:32:03.885267***

In [47]:
#%% VX + EP + EN 통계
work_name = "VX_EP"
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

print(f"***{work_name} 관련 통계를 위한 기본 파일을 만듭니다.")
pivot_list = []
df_vx_ep_list = []
index_columns = ['category', 'vx_no.', 'EP_form', 'EN_label', 'EN_No']

### .1 기본
for i, d in enumerate(df_v_list):    
    if index_columns: 
        
        df_vx = d[d['vx_no.'].notnull()] #vx 추출
        
        df_vx_ep = df_vx[df_vx['EP_form'].notnull()] #vx + EP 추출
        df_vx_ep_list.append(df_vx_ep) #VX  + EP 리스트 저장
        
        #피벗테이블 만들기
        #조합을 확인하기 위해서 없는 경우를 채움.      
        for column in index_columns:
            if pd.api.types.is_numeric_dtype(df[column]):
                df[column] = df[column].fillna(-1)
            else:
                df[column] = df[column].fillna('__MISSING__')
        cross_0 = pd.pivot_table(df_vx[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=True) #피벗테이블 생성
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        pivot_list.append(cross_0) #리스트에 넣기
                
result_df = pd.concat(pivot_list) #피벗을 하나로 연결
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

# 피벗 저장
print(f"***통계를 저장합니다.:    {datetime.now()}***")
out_file = dir_path / 'result_2025'/ f'{work_name}_statistics_{timestamp}.csv'
result_df.to_csv(out_file)

### .2 리스트에 문장 합하기. 검색용
print(f"***vx_sen_df를 만듭니다.:    {datetime.now()}***")

df_vx_sen_list = []
for i, (df, df_sen) in enumerate(zip(df_vx_ep_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    df_vx_sen_list.append(df_vx_sen)
    del df_vx_sen, df, df_sen
    gc.collect()
    
df_con = pd.concat(df_vx_sen_list)

print(f"***리스트를 저장합니다.:    {datetime.now()}***")
out_file = dir_path /'result_2025' / f'{work_name}_list_{timestamp}.csv'
df_con.to_csv(out_file)

***VX_EP 관련 통계를 위한 기본 파일을 만듭니다.
***통계를 저장합니다.:    2025-06-19 13:59:01.099559***
***vx_sen_df를 만듭니다.:    2025-06-19 13:59:01.317670***
***리스트를 저장합니다.:    2025-06-19 13:59:33.135662***

In [ ]:
#%% V+ EP + VX1 통계
work_name = "EP_VX1"
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

print(f"***{work_name} 통계를 위한 기본 파일을 만듭니다.")
df_ep_list = []
pivot_list = []
index_columns = ['category', 'V_label', 'EP_form', 'vx1_No']

for i, d in enumerate(df_v_list):    
    print(f"{i}.      파 일:{folder_name_list[i]}:     {datetime.now()}***")
    if index_columns: 
        df_vx = d[d['vx1_No'].notnull()] #vx 추출
        df_ep = df_vx[df_vx['EP_form'].notnull()]
        df_ep_list.append(df_ep)
        
        #피벗테이블
        for column in index_columns:      # 피벗 전처리정보 count를 위해서 빈값을 ''로 채우기
            df_vx[column] = df_vx[column].fillna('') 
        cross_0 = pd.pivot_table(df_vx[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False)
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        
        pivot_list.append(cross_0)
        
result_df = pd.concat(pivot_list)
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

print(f"***통계를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_statistics_' + timestamp + '.csv'
result_df.to_csv(out_file)

### .2 리스트에 문장 합하기. 검색용
print(f"***리스트를 저장합니다.:    {datetime.now()}***")

df_vx_sen_list = []
for i, (df, df_sen) in enumerate(zip(df_ep_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    print(f"{i}.***파 일:    {folder_name_list[i]}***")
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    df_vx_sen_list.append(df_vx_sen)
    del df_vx_sen, df, df_sen
    gc.collect()
    
df_con = pd.concat(df_vx_sen_list)

print(f"***리스트를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_list_' + timestamp + '.csv'
df_con.to_csv(out_file)
#%% VX +EP+ VX 통계
work_name = "VX_VX"
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

print(f"***{work_name} 관련 통계를 위한 기본 파일을 만듭니다.")
pivot_list = []
df_vx_list = []
index_columns = ['category', 'vx_no.', 'EP_form','vx1_No']

### .1 기본
for i, d in enumerate(df_v_list):
    print(f"{i}.      파 일:{folder_name_list[i]}:     {datetime.now()}***")   
    
    if index_columns: 
        
        df_vx = d[d['vx_no.'].notnull()&d['vx1_No'].notnull()] #vx vx 추출
        
        df_vx_list.append(df_vx) #VX  + EP 리스트 저장
        
        #피벗테이블 만들기
        for column in index_columns:      #피벗테이블 전 처리: 정보 count를 위해서 빈값을 ''로 채우기
            df_vx[column] = df_vx[column].fillna('') 
        cross_0 = pd.pivot_table(df_vx[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False) #피벗테이블 생성
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        pivot_list.append(cross_0) #리스트에 넣기
                
result_df = pd.concat(pivot_list) #피벗을 하나로 연결
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

# 피벗 저장
print(f"***통계를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_statistics_' + timestamp + '.csv'
result_df.to_csv(out_file)

### .2 리스트에 문장 합하기. 검색용
print(f"***vx_sen_df를 만듭니다.:    {datetime.now()}***")

df_vx_sen_list = []
for i, (df, df_sen) in enumerate(zip(df_vx_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    print(f"{i}.***파 일:    {folder_name_list[i]}***")
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    df_vx_sen_list.append(df_vx_sen)
    del df_vx_sen, df, df_sen
    gc.collect()
    
df_con = pd.concat(df_vx_sen_list)

print(f"***리스트를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_list_' + timestamp + '.csv'
df_con.to_csv(out_file)

In [ ]:

#%% VX + VX 통계
work_name = "VX_VX"
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

print(f"***{work_name} 관련 통계를 위한 기본 파일을 만듭니다.")
pivot_list = []
df_vx_list = []
index_columns = ['category', 'vx1_No', 'vx2_No']

### .1 기본
for i, d in enumerate(df_v_list):
    print(f"{i}.      파 일:{folder_name_list[i]}:     {datetime.now()}***")   
    
    if index_columns: 
        
        df_vx = d[d['vx1_No'].notnull()&d['vx2_No'].notnull()] #vx vx 추출
        
        df_vx_list.append(df_vx) #VX  + EP 리스트 저장
        
        #피벗테이블 만들기
        for column in index_columns:      #피벗테이블 전 처리: 정보 count를 위해서 빈값을 ''로 채우기
            df_vx[column] = df_vx[column].fillna('') 
        cross_0 = pd.pivot_table(df_vx[['ID']+index_columns], index=index_columns, aggfunc=len, fill_value=0, dropna=False) #피벗테이블 생성
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']] #존재하지 않는 조합은 지움
        pivot_list.append(cross_0) #리스트에 넣기
                
result_df = pd.concat(pivot_list) #피벗을 하나로 연결
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

# 피벗 저장
print(f"***통계를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_statistics2_' + timestamp + '.csv'
result_df.to_csv(out_file)

### .2 리스트에 문장 합하기. 검색용
print(f"***vx_sen_df를 만듭니다.:    {datetime.now()}***")

df_vx_sen_list = []
for i, (df, df_sen) in enumerate(zip(df_vx_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    print(f"{i}.***파 일:    {folder_name_list[i]}***")
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    df_vx_sen_list.append(df_vx_sen)
    
df_con = pd.concat(df_vx_sen_list)

print(f"***리스트를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_list2_' + timestamp + '.csv'
df_con.to_csv(out_file)

#%% VX 검색파일 만들기
work_name = "VX"
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

print(f"***{work_name} 관련 통계를 위한 기본 파일을 만듭니다.")
result_df_list = []
df_vx_list = []
index_columns = ['category', 'V_No', 'vx1_No']

### .1 기본
for i, d in enumerate(df_v_list):
    print(f"{i}.      파 일:{folder_name_list[i]}:     {datetime.now()}***")   
    
    if index_columns: 
        
        #df_vx = d[d['vx_no.'].isnull()&d['vx1_No'].notnull()&d['vx2_No'].isnull()] #vx 1개만 있는 f_v 추출
        df_vx = d[d['vx1_No'].notnull()] #vx 추출
        print(f"          파 일:{work_name}:  {len(df_vx)}개")   
        df_vx_list.append(df_vx) #VX  + EP 리스트 저장
        
        #피벗테이블 만들기
        for column in index_columns:      #피벗테이블 전 처리: 정보 count를 위해서 빈값을 ''로 채우기
            df_vx[column] = df_vx[column].fillna('') 
    grouped_df = df_vx.groupby(index_columns).size().reset_index(name='ID')
    
    result_df_list.append(grouped_df)
    del grouped_df, column
    gc.collect()
    
result_df = pd.concat(result_df_list) #피벗을 하나로 연결
result_df = result_df.reset_index()   # 인덱스를 다시 열로 변환
# 정보 덧붙이기 함수 호출
result_df = process_dataframe(result_df, df_category, df_v_label)

# 피벗 저장
print(f"***통계를 저장합니다.:    {datetime.now()}***")
out_file = dir_path + '/result/' + work_name +'_statistics_' + timestamp + '.csv'
result_df.to_csv(out_file)

del result_df, result_df_list
gc.collect()

### .2 리스트에 문장 합하기. 검색용
print(f"***vx_sen_df를 만듭니다.:    {datetime.now()}***")

for i, (df, df_sen) in enumerate(zip(df_vx_list, df_sen_list)):
    df_sen = df_sen[['sen_id', 'form']]
    print(f"{i}.***파 일:    {folder_name_list[i]}***")
    df_vx_sen = pd.merge(df_sen, df, how='right', on = 'sen_id')
    
    print(f"***리스트를 저장합니다.:    {datetime.now()}***")
    out_file = dir_path + '/result/' + folder_name_list[i][:-1] + '_' + work_name +'_' + timestamp + '.csv'
    df_vx_sen.to_csv(out_file)
    
    del df_vx_sen, df, df_sen
    gc.collect()