In [ ]:
## 2025.07.06 '-고'에 대한 논문 작성느라 만듦
from pathlib import Path
dir_path = Path(r"C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치")
v_folder = dir_path / "최신버전" / "v"
sen_folder = dir_path / "최신버전" / "sen"

from datetime import datetime
time = []#걸린 시간 체크 리스트
start_t = datetime.now() #시간 체크
time.append(datetime.now() - start_t) #시간간격 저장
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M") #시작 시간 저장

In [ ]:
import pandas as pd
for file in v_folder.glob('*.csv'):
    print(file)
#%% 1.1 v 파일 읽기: 55초 걸림.
df_v_list = []
for file in v_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        
        df_v_list.append(df)

df_v_list[2].rename(columns={'docu_id': 'file_id'}, inplace=True)

In [5]:
#%% 1.2 문장 파일 읽어오기
df_sen_list = []
for file in sen_folder.glob('*.csv'):
    print(file)
    
print('%%%%%1.2 문장 파일-sen2 읽기') 
for file in sen_folder.glob("*.csv"):
    with open(file, "r", encoding = "UTF-8") as f:
        df = pd.read_csv(f, low_memory=False)
        #'Unnamed:'를 포함하는 columns 삭제
        cols_to_drop = [col for col in df.columns if 'Unnamed:' in col]
        df = df.drop(columns=cols_to_drop)
        df_sen_list.append(df)
df_sen_list[2].rename(columns={'docu_id': 'file_id'}, inplace=True)

C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\sen\국립국어원 구어 말뭉치(버전 1.2)_일부(1,15)_sen2.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\sen\국립국어원 일상대화 말뭉치2020,2021_sen2.csv
C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\최신버전\sen\세종_문어_형태분석_말뭉치_sen2.csv
%%%%%1.2 문장 파일-sen2 읽기

In [24]:
df_v_list[2].head(100)

,ID,sen_id,word_id,word_id2,form/label,N_form,N_label,V_form,V_label,EP_form,...,v_loc_w,vx_0,vx_no.,EN_No,f_EN_No,file_id,category,V_form_0,V_label_0,V_No
0,12,AA0001.7,10,10,넓히/VV + 어/EF,NaN,NULL,넓히,VV,NULL,...,-1.0,NULL,-1,1401.0,1401.0,AA0001,신문,넓히,VV,3743
1,14,AA0001.8,2,2,세계/NNG + 적/XSN + 이/VCP + ㄴ/ETM,세계 + 적,XSN,이,VCP,NULL,...,-1.0,NULL,-1,2001.1,2001.1,AA0001,신문,이,VP,1001
2,23,AA0001.8,11,11,나서/VV + 었/EP + 다/EF + ./SF,NaN,NULL,나서,VV,었,...,-1.0,NULL,-1,1101.0,1101.0,AA0001,신문,나서,VV,3132
3,28,AA0001.9,5,5,사용하/VV + 는/ETM,NaN,NULL,사용하,VV,NULL,...,-1.0,NULL,-1,2001.2,2001.2,AA0001,신문,사용하,VV,3083
4,31,AA0001.9,8,8,디자인하/VV + 아/EC,NaN,NULL,디자인하,VV,NULL,...,-1.0,NULL,-1,20.0,20.0,AA0001,신문,디자인하,VV,4999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,388,AA0001.37,9,9,있/VA + 다/EF + ./SF,NaN,NULL,있,VA,NULL,...,-1.0,NULL,-1,1101.0,1101.0,AA0001,신문,있,VA,2001
96,399,AA0001.38,11,11,따르/VV + 아/EC,NaN,NULL,따르,VV,NULL,...,-1.0,NULL,-1,20.0,20.0,AA0001,신문,따르,VV,3028
97,401,AA0001.38,13,13,6/SN + 천/NR + 원/NNB + 이/VCP + 다/EF + ./SF,6 + 천 + 원,NNB,이,VCP,NULL,...,-1.0,NULL,-1,1101.0,1101.0,AA0001,신문,이,VP,1001
98,405,AA0001.39,4,4,2/SN + 배/NNG + 이/VCP + ㄴ/ETM,2 + 배,NNG,이,VCP,NULL,...,-1.0,NULL,-1,2001.1,2001.1,AA0001,신문,이,VP,1001
99,411,AA0001.40,4,4,넘/VV + 는다/EF + ./SF,NaN,NULL,넘,VV,NULL,...,-1.0,NULL,-1,1101.2,1101.2,AA0001,신문,넘,VV,3085

In [8]:
df_sen_list[2].head(10)

,ID,sen_id,form,file_id,Snum,category,자료명,저자,출판사,출판연도,구어/문어,매체,내용,분류기호
0,1,AA0001.5,1993/06/08,AA0001,5.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
1,2,AA0001.6,19,AA0001,6.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
2,3,AA0001.7,엠마누엘 웅가로 / 의상서 실내 장식품으로… 디자인 세계 넓혀,AA0001,7.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
3,4,AA0001.8,프랑스의 세계적인 의상 디자이너 엠마누엘 웅가로가 실내 장식용 직물 디자이너로 나섰다.,AA0001,8.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
4,5,AA0001.9,"웅가로는 침실과 식당, 욕실에서 사용하는 갖가지 직물제품을 디자인해 최근 파리의 갤...",AA0001,9.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
5,6,AA0001.10,"목욕가운부터 탁자보, 냅킨, 앞치마까지 그가 디자인한 작품들에서 두드러지는 것은 색...",AA0001,10.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
6,7,AA0001.11,"남미풍의 강렬한 원색끼리의 조화, 수채화 같이 안온한 배색 등 색의 분위기를 강조하...",AA0001,11.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
7,8,AA0001.12,"엠마누엘 웅가로는 ""실내 장식품을 디자인할 때 옷을 만들 때와는 다른 해방감을 느낀...",AA0001,12.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
8,9,AA0001.13,집은 창작의 원천이라는 그는 옷 못지않게 공간이 주는 미학을 중요시해 왔다.,AA0001,13.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115
9,10,AA0001.14,"매일 욕실에서 1시간 반 이상을 보낸다는 그는 체조와 텔레비전 시청, 식사까지 할 ...",AA0001,14.0,신문,조선일보 생활(93),조선일보사,조선일보사,1993,문어,신문,"보도·해설-생활, 과학",M1115

In [9]:
#누락값 채움. 
#object를 category형으로 바꿈. : 45초 걸림
exclude_cols = ['form/label', 'N_form', 'V_form', 'f_V_form']  # 제외할 열
for df in df_v_list:
    for col in df.columns:
        if col in exclude_cols:
            continue  # 제외할 열은 건너뛰기

        # 숫자형이면 -1로 채움
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(-1)

        # 문자열(object)이면 'NULL'로 채우고 고유값 적을 때만 category로
        elif pd.api.types.is_object_dtype(df[col]):
            df[col] = df[col].fillna('NULL')
            unique_ratio = df[col].nunique(dropna=False) / len(df)
            if unique_ratio < 0.5:
                df[col] = df[col].astype('category')

In [36]:
for i, df in enumerate(df_v_list):
    print(f"{i}: {len(df)}, v: {len(df[df['V_No']!= -1])}, E, {len(df[df['EN_No']!= -1])}, v-n: {len(df[df['N_form']==None])}" )

0: 3698172, v: 3669128, E, 3690747, v-n: 0
1: 3607347, v: 3587758, E, 3596121, v-n: 0
2: 4599514, v: 4574704, E, 4597601, v-n: 0

In [13]:
import numpy as np

### 추가 정보 붙이는 함수 선언
def process_dataframe(result_df):    
    # 피벗테이블을 일반 데이터프레임으로 변환
    if 'index' in result_df.columns:
        result_df = result_df.reset_index()
    
    # category 덧붙이기
    if ('category' in result_df.columns) & ('category_0' not in result_df.columns):    
        data = {
            "category": ["강의", "강의, 학술집담회", "낭독", "뉴스", "방송대화", "방송인터뷰", "토론",
                        "교육자료", "사회일반", "신문", "인문", "일상대화", "자연", "잡지", "체험기술",
                        "총류,일반", "허구", "협력적대화"],
            "category_0": ["공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어", "공적구어",
                        "문어", "문어", "문어", "문어", "사적구어", "문어", "문어", "문어",
                        "문어", "문어", "사적구어"]
        }
        df_category = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_category, on="category", how="left")

    # V_label 덧붙이기
    if ('V_label' in result_df.columns) & ('V_label_0' not in result_df.columns):
        data = {
            "V_label": ["VV", "VA", "VCN", "VCP", "XSV", "XSA", "VX"],
            "V_label_0": ["VV", "VA", "VA", "VP", "VV", "VA", "VX"]
        }
        df_v_label = pd.DataFrame(data)
        result_df = pd.merge(result_df, df_v_label, on="V_label", how="left")

    # EN 정보 덧붙이기
    if ('EN_No' in result_df.columns) & ('EN_No_0' not in result_df.columns):
        result_df['EN_No'] = pd.to_numeric(result_df['EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['EN_No_0'] = result_df['EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['EN_No_1'] = result_df['EN_No'] - result_df['EN_No_0']  # 소수점 이하만 남김

    # f_EN 정보 덧붙이기
    if ('f_EN_No' in result_df.columns) & ('f_EN_No_0' not in result_df.columns):
        result_df['f_EN_No'] = pd.to_numeric(result_df['f_EN_No'], errors='coerce')  # 'EN_No' 열을 숫자형으로 변환, 변환할 수 없는 값은 NaN으로 처리
        result_df['f_EN_No_0'] = result_df['f_EN_No'].apply(lambda x: int(x) if not np.isnan(x) else np.nan)  # 'EN_No_0' 열을 추가 (EN_No 내림)
        result_df['f_EN_No_1'] = result_df['f_EN_No'] - result_df['f_EN_No_0']  # 소수점 이하만 남김
        
    # EP 정보 덧붙이기
    if ('EP_form' in result_df.columns) & ('T' not in result_df.columns):
        result_df['T'] = result_df['EP_form'].str.contains('았|었')
        result_df['M'] = result_df['EP_form'].str.contains('겠|겄')
        result_df['H'] = result_df['EP_form'].str.contains('시')

    # f_EP 정보 덧붙이기
    if ('f_EP_form' in result_df.columns) & ('f_T' not in result_df.columns):
        result_df['f_T'] = result_df['f_EP_form'].str.contains('았|었')
        result_df['f_M'] = result_df['f_EP_form'].str.contains('겠|겄')
        result_df['f_H'] = result_df['f_EP_form'].str.contains('시')

    # V_No 정보 덧붙이기
    if ('V_No' in result_df.columns) & ('V_label' not in result_df.columns):
        # V_label 생성: V_No 값에 따라 부여
        def assign_v_label(v_no):
            if 0 <= v_no < 1000:
                return 'VX'
            elif 1000 <= v_no < 2000:
                return 'VC'
            elif 2000 <= v_no < 3000:
                return 'VA'
            elif 3000 <= v_no < 5000:
                return 'VV'
            else:
                return ''  # 혹시 범위 벗어난 경우 대비

        result_df['V_label'] = result_df['V_No'].apply(assign_v_label)
    
    return result_df

In [14]:
def generate_pivot_statistics(
    df_list,
    index_columns,
    process_fn=None,
    filter_fn=None,
):
    """
    여러 DataFrame에서 지정한 index_columns 기준으로 피벗 통계를 계산.

    Parameters:
        df_list (list of pd.DataFrame): 분석 대상 데이터프레임 리스트
        index_columns (list of str): 피벗 기준 열 목록
        process_fn (callable, optional): 결과 df 후처리 함수 (예: process_dataframe)
        filter_fn (callable, optional): 각 df에 필터를 적용할 함수 (예: lambda df: df[df['V_label'] == 'VX'])

    Returns:
        pd.DataFrame: 통합된 피벗 통계 결과
    """
    result_df_list = []
    print(f"*** 통계를 만듭니다. ***")
    
    for i, df in enumerate(df_list):
        print(f"{i}. 피벗 생성 중...")

        # 필터 함수가 있다면 적용
        if filter_fn:
            df = filter_fn(df)

        cross_0 = pd.pivot_table(
            df[['ID'] + index_columns],
            index=index_columns,
            aggfunc='count',
            fill_value=0,
            dropna=True,
            observed=False
        )
        cross_0 = cross_0[cross_0['ID'] != 0][['ID']]
        result_df_list.append(cross_0)

    result_df = pd.concat(result_df_list).reset_index()

    if process_fn:
        result_df = process_fn(result_df)

    return result_df

In [38]:
### 전체_동사_어미
prefix = "V_EN"
save_folder = '2025.07.05-고'
index_columns = ['V_No', 'EP_form','EN_label','EN_No']

result_df = generate_pivot_statistics(
    df_list=df_v_list,
    index_columns=index_columns,
    process_fn=process_dataframe,
)

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / save_folder / f'{prefix}_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

*** 통계를 만듭니다. ***
0. 피벗 생성 중...
1. 피벗 생성 중...
2. 피벗 생성 중...
***저장합니다.:    2025-07-06 15:40:11.454972***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_statistics_2025-07-06_15-40.csv (277,999행) ***

In [25]:
### 선어말어미나 vx부류와 결합하지 않은 절의 동사와 어미 결합 확인.
prefix = "V_EN"
save_folder = '2025.07.05-고'
index_columns = ['V_No', 'f_EP_form','f_EN_label','f_EN_No']

def filter(df):
    return df[(df['vx_len']==0) & (df['vx_no.']==-1) ]

result_df = generate_pivot_statistics(
    df_list=df_v_list,
    index_columns=index_columns,
    process_fn=process_dataframe,
    filter_fn=filter
)

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")
out_file = dir_path / save_folder / f'{prefix}_statistics_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

*** 통계를 만듭니다. ***
0. 피벗 생성 중...
1. 피벗 생성 중...
2. 피벗 생성 중...
***저장합니다.:    2025-07-06 12:21:40.407067***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_statistics_2025-07-06_12-21.csv (247,835행) ***

In [52]:
def expand_window(taget_df, df, window=2):
    """
    오류 후보 행들의 sen_id와 word_id2를 기준으로 주변 window만큼 확장한 행을 추출.
    """
    # 오류 후보들만 뽑고
    taget_row = taget_df[['sen_id', 'word_id2']].dropna().copy()
    taget_row['word_id2'] = taget_row['word_id2'].astype(int)

    # window 범위로 확장
    expanded_rows = []
    for _, row in taget_row.iterrows():
        sid = row['sen_id']
        wid = row['word_id2']
        for offset in range(-window, window + 1):
            expanded_rows.append((sid, wid + offset))

    # 중복 제거
    expanded_df = pd.DataFrame(expanded_rows, columns=['sen_id', 'word_id2']).drop_duplicates()

    # 기준 df와 merge
    df['word_id2'] = df['word_id2'].astype('Int64')  # Null 허용 정수로
    result_df = pd.merge(df, expanded_df, on=['sen_id', 'word_id2'], how='inner')
    result_df = result_df.sort_values(by=['sen_id', 'word_id2']).reset_index(drop=True)

    return result_df


def generate_sentence_df(
    df_list,
    df_sen_list,
    process_fn=None,
    filter_fn=None,
    window=0
):
    """
    DataFrame에서 필터를 수행한 결과를 문장과 합해서 출력

    Parameters:
        df_list (list of pd.DataFrame): 분석 대상 데이터프레임 리스트
        df_sen_list (list of pd.DataFrame): 합할 문장 데이터프레임 리스트
        process_fn (callable, optional): 결과 df 후처리 함수 (예: process_dataframe)
        filter_fn (callable, optional): 각 df에 필터를 적용할 함수 (예: lambda df: df[df['V_label'] == 'VX'])

    Returns:
        result_df_list: list of pd.DataFrame: 통합된 데이터프레임 리스트 결과
    """
    result_df_list = []
    print(f"*** 문장 통합 df를 만듭니다. ***")
    
    for i, (df, df_sen) in enumerate(zip(df_list, df_sen_list)):
        print(f"{i}. 통합 중...")

        # 필터 함수가 있다면 적용
        if filter_fn:
            taget_df = filter_fn(df)

            if window > 0:
                df = expand_window(taget_df, df, window)
            else: 
                df = taget_df

        df_sen = df_sen[['sen_id', 'form']]
        result_df = pd.merge(df_sen, df, how='right', on = 'sen_id')

        if process_fn:
            result_df = process_fn(result_df)
        
        print(f"{i}. 통합 완료..., 결과: {len(result_df)}")

        result_df_list.append(result_df)
    return result_df_list

In [53]:
### 선어말어미나 vx부류와 결합하지 않은 절의 동사와 어미 결합 확인. 문장 출력
prefix = "V_EN"
save_folder = '2025.07.05-고'
index_columns = ['V_No', 'f_EN_label','f_EN_No']

def my_filter2(df):
    return df[(df['vx_len']==0) & (df['vx_no.']==-1) & (df['f_EN_label']=='EC')& (df['EP_label']=='NULL')]

result_df_list = generate_sentence_df(
    df_list=df_v_list,
    df_sen_list=df_sen_list,
    process_fn=process_dataframe,
    filter_fn=my_filter2
)

*** 문장 통합 df를 만듭니다. ***
0. 통합 중...
0. 통합 완료..., 결과: 847721
1. 통합 중...
1. 통합 완료..., 결과: 939331
2. 통합 중...
2. 통합 완료..., 결과: 983110

In [ ]:
## 문장 파일 각각 저장하기.
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(f"***저장합니다.:    {datetime.now()}***")

for i, result_df in enumerate(result_df_list):
    out_file = dir_path / save_folder / f'{prefix}_sentence_{i}_{timestamp}.csv'
    result_df.to_csv(out_file, index=True, encoding='utf-8-sig')
    print(f"*** 저장 완료: {out_file} ({len(result_df):,}행) ***")

***저장합니다.:    2025-07-06 12:38:54.908650***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_sentence_0_2025-07-06_12-38.csv (847,721행) ***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_sentence_1_2025-07-06_12-38.csv (939,331행) ***
*** 저장 완료: C:\Users\yu2hy\OneDrive\◎2020_copus\가공_결과물\바른형태분석_말뭉치\2025.07.05-고\V_EN_sentence_2_2025-07-06_12-38.csv (983,110행) ***

In [55]:
### V_label이 VX이면서 vx_no가 -1이 아닌 오류  문장 출력
prefix = "VX_오류"
save_folder = '2025.07.05-고'
index_columns = ['V_No', 'f_EN_label','f_EN_No']

def my_filter_error(df):
    return df[(df['V_label']=='VX') & (df['vx_no.']==-1)]

result_df_list = generate_sentence_df(
    df_list=df_v_list,
    df_sen_list=df_sen_list,
    process_fn=process_dataframe,
    filter_fn=my_filter_error,
    window=2
)

*** 문장 통합 df를 만듭니다. ***
0. 통합 중...
0. 통합 완료..., 결과: 17730
1. 통합 중...
1. 통합 완료..., 결과: 16890
2. 통합 중...
2. 통합 완료..., 결과: 31381

In [56]:
##문장 파일 통합해서 저장하기
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
result_df = pd.concat(result_df_list)
out_file = dir_path / save_folder / f'{prefix}_sentence_{i}_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')

In [40]:
for i, df in enumerate(df_v_list):
    print(f"{i}, {len(df[df['V_label']=="VX"])}")

0, 437773
1, 434088
2, 574023

In [57]:
### 말－이 ＶＶ이면서 ＥＦ와　결합한　문장 출력
prefix = "말_VV_EF"
save_folder = '2025.07.05-고'

def my_filter_error(df):
    return df[(df['V_label']=='VV') & (df['V_form']=="말") & (df['f_EN_label']=="EF")]

result_df_list = generate_sentence_df(
    df_list=df_v_list,
    df_sen_list=df_sen_list,
    process_fn=process_dataframe,
    filter_fn=my_filter_error,
    window=2
)
##문장 파일 통합해서 저장하기
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
result_df = pd.concat(result_df_list)
out_file = dir_path / save_folder / f'{prefix}_sentence_{i}_{timestamp}.csv'
result_df.to_csv(out_file, index=True, encoding='utf-8-sig')

*** 문장 통합 df를 만듭니다. ***
0. 통합 중...
0. 통합 완료..., 결과: 1296
1. 통합 중...
1. 통합 완료..., 결과: 1116
2. 통합 중...
2. 통합 완료..., 결과: 1249